version: '3'
services:
  postgres_seller:
    image: postgres:15
    environment:
      POSTGRES_DB: seller_local
      POSTGRES_USER: seller_local
      POSTGRES_PASSWORD: seller_local
    ports:
      - "5432:5432"
    volumes:
      - postgres_seller_data:/var/lib/postgresql/data

  postgres_product:
    image: postgres:15
    environment:
      POSTGRES_DB: product_local
      POSTGRES_USER: product_local
      POSTGRES_PASSWORD: product_local
    ports:
      - "5433:5432"
    volumes:
      - postgres_product_data:/var/lib/postgresql/data

  postgres_order:
    image: postgres:15
    environment:
      POSTGRES_DB: order_local
      POSTGRES_USER: order_local
      POSTGRES_PASSWORD: order_local
    ports:
      - "5434:5432"
    volumes:
      - postgres_order_data:/var/lib/postgresql/data

volumes:
  postgres_seller_data:
  postgres_product_data:
  postgres_order_data:
