spring:

  # profile
  profiles:
    group:
      production:
        - production
      develop:
        - develop
      local:
        - local
      default: local

  # datasource
  datasource:
    driver-class-name: org.postgresql.Driver

  # jpa
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

aws:
  sesv2:
    region: ap-northeast-2

springdoc:
  use-fqn: true
